### ISSUE TITLE
Interface vlan on #0

### ISSUE THREAD

**Issue by meandus** [gabstopper/ansible-stonesoft#11]
I tried to create interface vlan 609 on interface 0

Ansible configure interface 0 without Vlan

it's ok for others interfaces

      -   cluster_virtual: XXX.1
          comment: WAN_Transit
          interface_id: '0'
          macaddress: 'xx:xx:xx:xx:xx:xx'
          network_value: XXX/28
          nodes:
          -   address: XXX.2
              network_value: XXX/28
              nodeid: 1
          -   address: XXX.3
              network_value: XXX/28
              nodeid: 2
          vlan_id: '609'

I think it's because of primary_mgt and backup_mgt define normally on vlan interface but my workaround was to define 0 instead of 0.608

**Comment by gabstopper** [comment]
Hi Remy,
Yes, this is by design. If an interface is created without VLANs, you cannot convert it to a VLAN interface without first removing the interface addresses (same with the SMC). So in the case of the ansible run, the VLAN id is ignored since the interface already exists as a standard interface. I have resolved creating a cluster and using the VLAN id as the management interface so this shouldn't be a problem anymore. Will update this case when I perform the push.

**Comment by gabstopper** [comment]
Hi Remy,
This shouldn't be an issue with the latest commit that supports creating a cluster with a VLAN interface defined as a VLAN interface. Please confirm this works for you.

**Comment by meandus** [comment]
almost good 

  "msg": "Impossible to store the element fwStore13. Element appears invalid: You must enter a MAC Address for the Interface 0 Physical Interface."

In your facts, you have put one mac per Vlan and not Mac per Interface and what about Packet Dispatch (CVI_MODE)

**Comment by gabstopper** [comment]
Thanks for catching the mac output and cvi, will update the facts output.

Also, do you have a yaml configuration where you can duplicate this message:

"msg": "Impossible to store the element fwStore13. Element appears invalid: You must enter a MAC Address for the Interface 0 Physical Interface."

**Comment by gabstopper** [comment]
ok I looked at this and the macaddress output. It is actually 'by design' (although this is where I question the design :)). In order to make the yaml "flat", i've collapsed a VLAN interface so it represents the other interfaces. So there is technically not a definition for a 'top level' interface with the VLAN in yaml. This can be changed if you think this makes more sense. It is definitely in line more with SMC. So for example two VLANs on the same physical interface:

```
-   cluster_virtual: 22.22.22.254
     interface_id: '21'
     macaddress: 02:02:02:20:20:20
     network_value: 22.22.22.0/24
     nodes:
     -   address: 22.22.22.1
         network_value: 22.22.22.0/24
          nodeid: 1
      -   address: 22.22.22.2
          network_value: 22.22.22.0/24
          nodeid: 2
     vlan_id: '21'
  -   cluster_virtual: 21.21.21.254
      interface_id: '21'
      macaddress: 02:02:02:20:20:20
      network_value: 21.21.21.0/24
      nodes:
      -   address: 21.21.21.1
          network_value: 21.21.21.0/24
          nodeid: 1
      -   address: 21.21.21.2
          network_value: 21.21.21.0/24
          nodeid: 2
      vlan_id: '20'
```

Here is an option which i'm learning towards that might make the most sense and is a little closer to how the creation constructor maps the fields. Does this make sense to you? It adds one additional layer of nesting but I think logically might better represent the interface, especially if you need to be able to modify top level settings:
```
-   interface_id: '21'
     macaddress: 02:02:02:02:02:02
     cvi_mode: packetdispatch
     interfaces:
     -   cluster_virtual: 22.22.22.254
          network_value: 22.22.22.0/24
          nodes:
          -   address: 22.22.22.1
              network_value: 22.22.22.0/24
              nodeid: 1
          -   address: 22.22.22.2
              network_value: 22.22.22.0/24
              nodeid: 2
          vlan_id: '21'
     -   cluster_virtual: 21.21.21.254
          network_value: 21.21.21.0/24
          nodes:
           -   address: 21.21.21.1
               network_value: 21.21.21.0/24
               nodeid: 1
           -   address: 21.21.21.2
               network_value: 21.21.21.0/24
               nodeid: 2
           vlan_id: '20'
```
Do you have a preference for this last format? This would change the syntax slightly, but provide the ability to also control any top level VLAN interface settings also.

**Comment by meandus** [comment]
Yes this last format is much better and logical because its useless to define macaddr per vlan. In my case I have 3 vlans on the same interface.

The first vlan is also mgt
The second is bkp mgt


Regards
RÉMY 

Le 19 mars 2018 13:24:27 GMT+01:00, David LePage <notifications@github.com> a écrit :
>ok I looked at this and the macaddress output. It is actually 'by
>design' (although this is where I question the design :)). In order to
>make the yaml "flat", i've collapsed a VLAN interface so it represents
>the other interfaces. So there is technically not a definition for a
>'top level' interface with the VLAN in yaml. This can be changed if you
>think this makes more sense. It is definitely in line more with SMC. So
>for example two VLANs on the same physical interface:
>
>```
>-   cluster_virtual: 22.22.22.254
>     interface_id: '21'
>     macaddress: 02:02:02:20:20:20
>     network_value: 22.22.22.0/24
>     nodes:
>     -   address: 22.22.22.1
>         network_value: 22.22.22.0/24
>          nodeid: 1
>      -   address: 22.22.22.2
>          network_value: 22.22.22.0/24
>          nodeid: 2
>     vlan_id: '21'
>  -   cluster_virtual: 21.21.21.254
>      interface_id: '21'
>      macaddress: 02:02:02:20:20:20
>      network_value: 21.21.21.0/24
>      nodes:
>      -   address: 21.21.21.1
>          network_value: 21.21.21.0/24
>          nodeid: 1
>      -   address: 21.21.21.2
>          network_value: 21.21.21.0/24
>          nodeid: 2
>      vlan_id: '20'
>```
>
>Here is an option which i'm learning towards that might make the most
>sense and is a little closer to how the creation constructor maps the
>fields. Does this make sense to you? It adds one additional layer of
>nesting but I think logically might better represent the interface,
>especially if you need to be able to modify top level settings:
>```
>-   interface_id: '21'
>     macaddress: 02:02:02:02:02:02
>     cvi_mode: packetdispatch
>     interfaces:
>     -   cluster_virtual: 22.22.22.254
>          network_value: 22.22.22.0/24
>          nodes:
>          -   address: 22.22.22.1
>              network_value: 22.22.22.0/24
>              nodeid: 1
>          -   address: 22.22.22.2
>              network_value: 22.22.22.0/24
>              nodeid: 2
>          vlan_id: '21'
>     -   cluster_virtual: 21.21.21.254
>          network_value: 21.21.21.0/24
>          nodes:
>           -   address: 21.21.21.1
>               network_value: 21.21.21.0/24
>               nodeid: 1
>           -   address: 21.21.21.2
>               network_value: 21.21.21.0/24
>               nodeid: 2
>           vlan_id: '20'
>```
>Do you have a preference for this last format? This would change the
>syntax slightly, but provide the ability to also control any top level
>VLAN interface settings also.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gabstopper/ansible-stonesoft/issues/11#issuecomment-374194164

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by gabstopper** [comment]
This would be how a NDI only interface would be defined (with VLANs):
```yaml
- cvi_mode: null
  interface_id: 2
  interfaces:
  - nodes:
    - address: 1.1.1.1
      network_value: 1.1.1.0/24
      nodeid: 1
    - address: 1.1.1.2
      network_value: 1.1.1.0/24
      nodeid: 2
    vlan_id: 20
    zone_ref: vlan 20 zone
  - nodes:
    - address: 2.1.1.1
      network_value: 2.1.1.0/24
      nodeid: 1
    - address: 2.1.1.2
      network_value: 2.1.1.0/24
      nodeid: 2
    vlan_id: 21
    zone_ref: vlan21 zone
  zone_ref: my_interface_zone
```

Without VLANs:
```yaml
- interface_id: 2
  interfaces:
  - nodes:
    - address: 1.1.1.1
      network_value: 1.1.1.0/24
      nodeid: 1
    - address: 1.1.1.2
      network_value: 1.1.1.0/24
      nodeid: 2
  zone_ref: my_interface_zone
```

**Comment by gabstopper** [comment]
CVI interfaces with VLAN:
```yaml
- cluster_virtual: 1.1.1.254
  cvi_mode: packetdispatch
  interface_id: 2
  interfaces:
  - nodes:
    - address: 1.1.1.1
      network_value: 1.1.1.0/24
      nodeid: 1
    - address: 1.1.1.2
      network_value: 1.1.1.0/24
      nodeid: 2
    vlan_id: 20
    zone_ref: vlan 20 zone
  - nodes:
    - address: 2.1.1.1
      network_value: 2.1.1.0/24
      nodeid: 1
    - address: 2.1.1.2
      network_value: 2.1.1.0/24
      nodeid: 2
    vlan_id: 21
    zone_ref: vlan21 zone
  macaddress: 02:02:02:02:02:02
  network_value: 1.1.1.0/24
```
and finally, CVI interfaces, no VLAN:
```yaml
- cluster_virtual: 1.1.1.254
  cvi_mode: packetdispatch
  interface_id: 2
  interfaces:
  - nodes:
    - address: 1.1.1.1
      network_value: 1.1.1.0/24
      nodeid: 1
    - address: 1.1.1.2
      network_value: 1.1.1.0/24
      nodeid: 2
  macaddress: 02:02:02:02:02:02
  network_value: 1.1.1.0/24
  zone_ref: interface level zone
```
