### ISSUE TITLE
Remove Element

### ISSUE THREAD

**Issue by meandus** [gabstopper/ansible-stonesoft#13]
Hi,
How is it possible to remove an element from a group ?
How is it possible to delete an element from SMC ?

Regards :)

**Comment by gabstopper** [comment]
Will have to add the functionality to add to a group but you can use network_element.yml to delete an element:
```yaml
- name: Delete network elements. Use a list of elements by name
  network_element:
    smc_logging:
        level: 10
        path: /Users/davidlepage/Downloads/ansible-smc.log
    state: absent
    elements:
      - group:
          - mygroup
          - newgroupa
      - host:
          - hosta
          - hostb
      - network:
          - networka
      - address_range:
          - myrange
      - interface_zone:
          - myzone
      - domain_name:
          - mydomain.com
      - router:
          - myrouter
      - ip_list:
          - myiplist
```
https://github.com/gabstopper/ansible-stonesoft/blob/master/playbooks/network_element.yml
