### ISSUE TITLE
ospf error

### ISSUE THREAD

**Issue by meandus** [gabstopper/ansible-stonesoft#23]
"module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_mBA8MR/ansible_module_engine.py\", line 1552, in <module>\n    main()\n  File \"/tmp/ansible_mBA8MR/ansible_module_engine.py\", line 1549, in main\n    StonesoftEngine()\n  File \"/tmp/ansible_mBA8MR/ansible_module_engine.py\", line 701, in __init__\n    super(StonesoftEngine, self).__init__(self.module_args, supports_check_mode=True)\n  File \"/tmp/ansible_mBA8MR/ansible_modlib.zip/ansible/module_utils/stonesoft_util.py\", line 449, in __init__\n  File \"/tmp/ansible_mBA8MR/ansible_module_engine.py\", line 1034, in exec_module\n    self.cache.get('ospfv2_area', ospf_area.get('name'))):\n  File \"/usr/lib/python2.7/site-packages/smc_python-0.6.1-py2.7.egg/smc/core/route.py\", line 472, in add_ospf_area\n    return self._add_gateway_node('ospfv2_area', routing_node_gateway, network)\n  File \"/usr/lib/python2.7/site-packages/smc_python-0.6.1-py2.7.egg/smc/core/route.py\", line 604, in _add_gateway_node\n    if self.related_element_type == 'tunnel_interface':\n  File \"/usr/lib/python2.7/site-packages/smc_python-0.6.1-py2.7.egg/smc/base/model.py\", line 372, in __getattr__\n    % (self.__class__, key))\nAttributeError: <class 'smc.core.route.Routing'> object has no attribute 'related_element_type'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0

the interface i'm trying to add is not a tunnel interface, it's a vlan interface
name of the area is area0
when it's already done in SMC, it's perfect, when it's not done ... there is an error

**Comment by meandus** [comment]
develop branch ... 

      ospf:
        enabled: true
        ospf_areas:
        - interface_id: "{{ '4.2' + '%02d'|format(item.value.id|int) + '3' }}"
          name: area0
          network: 10.2.{{ item.value.id }}.16/29
        - interface_id: "{{ '4.1' + '%02d'|format(item.value.id|int) + '2' }}"
          name: area0
          network: 10.1.{{ item.value.id }}.8/29
        ospf_profile: OSPF_profile_NC1_redistri_BGP_BU_mut_A
        router_id: 10.1.0.46

**Comment by gabstopper** [comment]
Hi Remy,
This one was known and I hadn't yet updated the develop branch to address this. However, I just pushed the latest so could you try this operation again? This issue actually exists in the smc-python library and is a backwards compatibility issue with an attribute introduced in 6.3.x. So please grab the latest develop branch and you I have also pushed a new smc-python release which you can get:
```
pip install smc-python
```

Version should be 0.6.1.

**Comment by meandus** [comment]
So

I pulled The latest ansible-stonesoft in dévelop branch and pulled smc-python 0.61 and The issue is still there. This server has no access to pip.

Regards
RÉMY 

Le 19 juin 2018 03:21:54 GMT+02:00, David LePage <notifications@github.com> a écrit :
>Hi Remy,
>This one was known and I hadn't yet updated the develop branch to
>address this. However, I just pushed the latest so could you try this
>operation again? This issue actually exists in the smc-python library
>and is a backwards compatibility issue with an attribute introduced in
>6.3.x. So please grab the latest develop branch and you I have also
>pushed a new smc-python release which you can get:
>```
>pip install smc-python
>```
>
>Version should be 0.6.1.
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gabstopper/ansible-stonesoft/issues/23#issuecomment-398244390

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by gabstopper** [comment]
Which version of SMC are you using?

**Comment by meandus** [comment]
my SMC is 6.2.2 currently


Le 19/06/2018 à 13:40, David LePage a écrit :

**Comment by gabstopper** [comment]
Hi Remy,
I just tested with 6.2.2 and it works properly. Can you remove the existing smc-python and reload 0.6.1? Here was my output:
```
changed: [localhost] => {
    "changed": true, 
    "engine": {}, 
    "failed": false, 
    "invocation": {
        "module_args": {
            "antispoofing_network": null, 
            "antivirus": false, 
            "backup_heartbeat": null, 
            "backup_mgt": null, 
            "bgp": {
                "enabled": false, 
                "router_id": null
            }, 
            "cluster_mode": null, 
            "comment": null, 
            "default_nat": false, 
            "delete_undefined_interfaces": false, 
            "domain_server_address": [], 
            "file_reputation": false, 
            "interfaces": [
                {
                    "interface_id": "0", 
                    "interfaces": [
                        {
                            "nodes": [
                                {
                                    "address": "1.1.1.1", 
                                    "network_value": "1.1.1.0/24", 
                                    "nodeid": 1
                                }
                            ]
                        }
                    ]
                }
            ], 
            "location": null, 
            "log_server": null, 
            "name": "fw", 
            "netlinks": [], 
            "ospf": {
                "enabled": true, 
                "ospf_areas": [
                    {
                        "interface_id": 0, 
                        "name": "area0", 
                        "network": "1.1.1.0/24"
                    }, 
                    {
                        "interface_id": 1, 
                        "name": "area0", 
                        "network": "10.1.0.0/24"
                    }
                ], 
                "ospf_profile": "testprofile", 
                "router_id": "10.1.0.46"
            }, 
            "policy_vpn": null, 
            "primary_heartbeat": null, 
            "primary_mgt": "0", 
            "skip_interfaces": false, 
            "smc_address": null, 
            "smc_alt_filepath": null, 
            "smc_api_key": null, 
            "smc_api_version": null, 
            "smc_domain": null, 
            "smc_extra_args": null, 
            "smc_logging": {
                "level": 10, 
                "path": "ansible-smc.log"
            }, 
            "smc_timeout": 30, 
            "snmp": {}, 
            "state": "present", 
            "tags": null, 
            "type": "single_fw"
        }
    }, 
    "state": [
        {
            "action": "updated", 
            "name": "ospf", 
            "type": "configuration"
        }, 
        {
            "action": "updated", 
            "name": "interface 0", 
            "type": "ospfv2_area"
        }, 
        {
            "action": "updated", 
            "name": "interface 1", 
            "type": "ospfv2_area"
        }
    ]
}
```

The playbook:
```
- name: Firewall Template
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Layer 3 FW template
    engine:
      smc_logging:
        level: 10
        path: ansible-smc.log
      antivirus: false
      bgp:
        enabled: false
        router_id: null
      default_nat: false
      file_reputation: false
      interfaces:
      - interface_id: '0'
        interfaces:
        - nodes:
          - address: 1.1.1.1
            network_value: 1.1.1.0/24
            nodeid: 1
      name: fw
      ospf:
        enabled: true
        ospf_areas:
        - interface_id: 0
          name: area0
          network: 1.1.1.0/24
        - interface_id: 1
          name: area0
          network: 10.1.0.0/24
        ospf_profile: testprofile
        router_id: 10.1.0.46
      primary_mgt: '0'
      type: single_fw
```
