### ISSUE TITLE
Enable interface as IPsec endpoint 

### ISSUE THREAD

**Issue by sebbbastien** [gabstopper/ansible-stonesoft#26]
Hi David,

I'm working with develop branch (I need netlinks).

Based on documentation, old [l3fw module](https://ansible-stonesoft.readthedocs.io/en/develop/modules/l3fw_module.html) it was possible to enable interface as IPsec Endpoint with `interfaces > enable_vpn` option.

Using actual [engine module](https://ansible-stonesoft.readthedocs.io/en/develop/modules/engine_module.html), this option disappear.
How to enable IPsec endpoint using engine module?
(My engine does not have a classic default route but two or more Netlinks and an Outbound Multi Link.)

Best regards,

Sébastien B.

**Comment by gabstopper** [comment]
Hi Sebastien,
Thanks for noticing that, I just looked through and indeed it is not in the new engine module. I will have to add it based on the new interface layout but will make it an option on CVI, NDI and VLAN interfaces. Do you have a timeline? It is something I should be able to complete by end of week.

**Comment by sebbbastien** [comment]
Hi David,
I need this feature for mid-February, so you have time.

Thanks for your help.

**Comment by sebbbastien** [comment]
Hi David,

Do you had time to work on this feature?

Best regards,

**Comment by gabstopper** [comment]
Hi Sebastien, 
I will have this feature and contact address available in the next couple of days. Will reply back once tested and posted.

**Comment by gabstopper** [comment]
Hi Sebastien,
I implemented this but due to some changes in v6.5.x will need to make some additional modifications for policy_vpn functionality. What version of SMC are you currently using?

**Comment by sebbbastien** [comment]
Hi David,

I have both 6.4.5 and 6.5.1 for development tests, but I think end-customer is running 6.5.

**Comment by sebbbastien** [comment]
Hi David,

Customer SMC is already in 6.5.1.

**Comment by gabstopper** [comment]
Hi sebasstien,
The latest develop branch resolves this issue. Here is an example:

```yaml
- name: Firewall Template
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Layer 3 FW template
    engine:
      smc_logging:
        level: 10
        path: ansible-smc.log
      antivirus: false
      bgp:
        enabled: false
        router_id: null
      default_nat: false
      enable_vpn:
      - 2.2.2.2
      file_reputation: false
      interfaces:
      - interface_id: '0'
        interfaces:
        - nodes:
          - dynamic: true
            dynamic_index: 1
      - interface_id: '1'
        interfaces:
        - nodes:
          - address: 1.1.1.1
            network_value: 1.1.1.0/24
            nodeid: 1
      - interface_id: '2'
        interfaces:
        - nodes:
          - address: 2.2.2.2
            network_value: 2.2.2.0/24
            nodeid: 1
          vlan_id: '2'
      name: foofw
      ospf:
        enabled: false
        router_id: null
      primary_mgt: '1'
      type: single_fw
```
The docs have been updated also. 

You can add the top level param `enable_vpn` as a list of IP addresses for which to enable VPN.
