### ISSUE TITLE
engine task failed to create a firewall with a DHCP interface as primary_mgt

### ISSUE THREAD

**Issue by sebbbastien** [gabstopper/ansible-stonesoft#31]
Hi,

The engine task is able to create a firewall with this configuration:
![image](https://user-images.githubusercontent.com/5331611/54871831-00d9af00-4dbb-11e9-9769-b298b5efdc9c.png)

With this configuration:
```
ok: [TestFW -> localhost] => {
    "changed": false,
    "engine_cfg": {
        "antivirus": false,
        "backup_mgt": null,
        "file_reputation": false,
        "interfaces": [
            {
                "comment": "Internet",
                "interface_id": 0,
                "interfaces": [
                    {
                        "nodes": [
                            {
                                "dynamic": true,
                                "dynamic_index": 1
                            }
                        ]
                    }
                ]
            },
            {
                "comment": "LAN",
                "interface_id": 1,
                "interfaces": [
                    {
                        "nodes": [
                            {
                                "address": "10.0.1.1",
                                "network_value": "10.0.1.0/24",
                                "nodeid": 1
                            }
                        ]
                    }
                ]
            }
        ],
        "location": "Internet",
        "name": "TestFW",
        "primary_mgt": 0,
        "type": "single_fw"
    },
    "invocation": {
        "module_args": {
            "lan_addr": "10.0.1.0/24",
            "site_id": "TestFW"
        }
    }
}
```

But fail with this one:
![image](https://user-images.githubusercontent.com/5331611/54871824-df78c300-4dba-11e9-8ca4-cc10b4eada78.png)

```
fatal: [C0001 -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "antispoofing_network": null,
            "antivirus": false,
            "backup_heartbeat": null,
            "backup_mgt": null,
            "bgp": null,
            "cluster_mode": null,
            "comment": null,
            "default_nat": null,
            "delete_undefined_interfaces": false,
            "domain_server_address": [],
            "enable_vpn": [],
            "file_reputation": false,
            "interfaces": [
                {
                    "comment": "Internet",
                    "interface_id": 0,
                    "interfaces": [
                        {
                            "nodes": [
                                {
                                    "dynamic": true,
                                    "dynamic_index": 1
                                }
                            ]
                        }
                    ]
                },
                {
                    "comment": "LAN",
                    "interface_id": 1,
                    "interfaces": [
                        {
                            "nodes": [
                                {
                                    "address": "10.0.1.1",
                                    "network_value": "10.0.1.0/24",
                                    "nodeid": 1
                                }
                            ]
                        }
                    ]
                }
            ],
            "location": "Internet",
            "log_server": null,
            "name": "C0001",
            "netlinks": [],
            "ospf": null,
            "policy_vpn": null,
            "primary_heartbeat": null,
            "primary_mgt": "0",
            "skip_interfaces": false,
            "smc_address": null,
            "smc_alt_filepath": null,
            "smc_api_key": null,
            "smc_api_version": null,
            "smc_domain": null,
            "smc_extra_args": null,
            "smc_logging": null,
            "smc_timeout": 30,
            "snmp": {},
            "state": "present",
            "tags": null,
            "type": "single_fw"
        }
    },
    "msg": "Impossible to store the element C0001. Element appears invalid: C0001 Single Firewall cannot have a dynamic IP address on an Interface that is used for Identity for Authentication Requests."
}
```

The only change is the primary_mgt value, 1 for the first (static ip), 0 for the second (dhcp).

I have a workaround available, there is no urgency on my side.

Best regards,

**Comment by gabstopper** [comment]
Hi Sebastien, thanks for the report. I see that the engine module is too strict with respects to allowing kwargs for node configurations and in the case of DHCP as management, we need to set a second interface as the interface for 'auth_requests'. In the SMC it's this field:

![image](https://user-images.githubusercontent.com/14811349/55022681-1f14fa00-4fc9-11e9-87ee-73df6b2dee7f.png)

I have updated the engine module to support this now. Once I push the update you will be able to resolve this by adding 'auth_request=True' to your static IP address interface:

```
- name: Firewall Template
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Layer 3 FW template
    engine:
      smc_logging:
        level: 10
        path: ansible-smc.log
      antivirus: false
      bgp:
        enabled: false
        router_id: null
      default_nat: false
      enable_vpn:
      - First DHCP Interface ip
      file_reputation: false
      interfaces:
      - interface_id: '1'
        interfaces:
        - nodes:
          - address: 1.1.1.1
            network_value: 1.1.1.0/24
            nodeid: 1
            auth_request: True
      - interface_id: '0'
        interfaces:
        - nodes:
          - dynamic: true
            dynamic_index: 1
      name: _dhcpfw2
      ospf:
        enabled: false
        router_id: null
      primary_mgt: '0'
      type: single_fw
```

**Comment by gabstopper** [comment]
Hi Sebastien, I have just updated the dev branch with this fix. You can now add additional attributes to a node as long as you have the minimum required. 

Here is an example:

```
- name: Firewall Template
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Layer 3 FW template
    engine:
      smc_logging:
        level: 10
        path: ansible-smc.log
      antivirus: false
      bgp:
        enabled: false
        router_id: null
      default_nat: false
      enable_vpn:
      - First DHCP Interface ip
      file_reputation: false
      interfaces:
      - interface_id: '1'
        interfaces:
        - nodes:
          - address: 1.1.1.1
            network_value: 1.1.1.0/24
            nodeid: 1
            auth_request: True
      - interface_id: '0'
        interfaces:
        - nodes:
          - dynamic: true
            dynamic_index: 1
      name: _dhcpfw2
      ospf:
        enabled: false
        router_id: null
      primary_mgt: '0'
      auth_request: '1'
      type: single_fw
```

Note that this requires the latest smc-python 0.7.0-b7 from the dev branch, just posted.
